app = 'uek-planzajec-v3'
primary_region = 'waw'

[[services]]
internal_port = 3001
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
handlers = ["tls"]
port = 443
tls_options = { "alpn" = ["h2"] }

[mounts]
source = "uek_cache"
destination = "/uek_cache"
initial_size = "1gb"
snapshot_retention = 1


[[vm]]
size = 'shared-cpu-1x'
